name: pagination_view
description: Flutter package to simplify pagination of list of items from the internet.
version: 2.0.0-nullsafety.0
issue_tracker: https://github.com/excogitatr/pagination_view/issues
homepage: https://github.com/excogitatr/pagination_view

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  effective_dart: ^1.3.0

  # Testing
  bloc_test: ^8.0.0-nullsafety.1
  mockito: ^5.0.0
