name: pagination_view
description: Flutter package to simplify pagination of list of items from the internet.
version: 1.0.3+1
issue_tracker: https://github.com/excogitatr/pagination_view/issues
homepage: https://github.com/excogitatr/pagination_view

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  bloc: ^5.0.1
  flutter_bloc: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  effective_dart: ^1.2.3

  # Testing
  bloc_test: ^6.0.1
  mockito: ^4.1.1
