name: pagination_view
description: Flutter package to simplify pagination of list of items from the internet.
version: 0.1.0
homepage: https://github.com/excogitatr/pagination_view

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter: